use std::fs::OpenOptions;
use std::path::{Path, PathBuf};

use super::{CompleteHistory, HistoryError};
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct HistoryDocument {
    version: u32,
    history: CompleteHistory,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    archived: Option<Vec<CompleteHistory>>,
}

const HISTORY_LOCK_FILE_NAME: &str = ".history.lock";
const LEGACY_MAX_RECORDED_WINDOWS: usize = 12;

#[derive(Clone)]
pub(crate) struct HistoryStore {
    root: PathBuf,
}

impl HistoryStore {
    pub(crate) fn new(app_data_dir: &Path) -> Self {
        Self {
            root: app_data_dir.join("provider-history"),
        }
    }

    pub(crate) fn load(
        &self,
        provider_id: &str,
        account_id: &str,
    ) -> Result<Option<CompleteHistory>, HistoryError> {
        Ok(self
            .read_document(provider_id, account_id)?
            .map(|document| document.history))
    }

    fn read_document(
        &self,
        provider_id: &str,
        account_id: &str,
    ) -> Result<Option<HistoryDocument>, HistoryError> {
        let path = self.document_path(provider_id, account_id)?;
        let _lock_file = self.lock()?;
        self.read_document_locked(&path, account_id)
    }

    fn read_document_locked(
        &self,
        path: &Path,
        account_id: &str,
    ) -> Result<Option<HistoryDocument>, HistoryError> {
        let content = match std::fs::read_to_string(path) {
            Ok(content) => content,
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
            Err(_) => return Err(HistoryError::StorageRead),
        };
        let value: serde_json::Value =
            serde_json::from_str(&content).map_err(|_| HistoryError::StorageInvalid)?;
        // Unknown formats may belong to a newer app. Leave them in place.
        if !matches!(
            value.get("version").and_then(serde_json::Value::as_u64),
            Some(1 | 2 | 3)
        ) {
            return Err(HistoryError::StorageInvalid);
        }
        let document = serde_json::from_value::<HistoryDocument>(value)
            .ok()
            .filter(|document| {
                let histories: Vec<_> = std::iter::once(&document.history)
                    .chain(document.archived.iter().flatten())
                    .collect();
                (document.version == 2) == document.archived.is_some()
                    && histories.len() <= LEGACY_MAX_RECORDED_WINDOWS
                    && histories
                        .iter()
                        .all(|history| valid_history(history, account_id))
                    && !histories.iter().enumerate().any(|(index, history)| {
                        histories[..index]
                            .iter()
                            .any(|previous| same_period(history, previous))
                    })
            });
        if let Some(document) = document {
            return Ok(Some(document));
        }

        let backup = path.with_extension(format!("json.{}.invalid", uuid::Uuid::new_v4()));
        std::fs::rename(path, backup).map_err(|error| {
            log::error!(
                "cursor damaged history could not be preserved: {:?}",
                error.kind()
            );
            HistoryError::StorageWrite
        })?;
        log::error!(
            "cursor history validation failed; original document preserved as an .invalid file"
        );
        Err(HistoryError::StorageInvalid)
    }

    /// Clear only this account's cached result. External credentials are untouched.
    pub(crate) fn clear(&self, provider_id: &str, account_id: &str) -> Result<(), HistoryError> {
        let path = self.document_path(provider_id, account_id)?;
        let _lock_file = self.lock()?;
        match std::fs::remove_file(&path) {
            Ok(()) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(_) => return Err(HistoryError::StorageWrite),
        }
        // Explicit removal also clears the same account's quarantined snapshots.
        // Match only the UUID filename shape generated by read_document_locked.
        let entries = match std::fs::read_dir(path.parent().ok_or(HistoryError::InvalidStorageKey)?)
        {
            Ok(entries) => entries,
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(()),
            Err(_) => return Err(HistoryError::StorageWrite),
        };
        let prefix = format!("{account_id}.json.");
        for entry in entries {
            let entry = entry.map_err(|_| HistoryError::StorageWrite)?;
            let name = entry.file_name();
            let quarantine_id = name
                .to_str()
                .and_then(|name| name.strip_prefix(&prefix))
                .and_then(|name| name.strip_suffix(".invalid"));
            if quarantine_id.is_some_and(|id| {
                uuid::Uuid::parse_str(id).is_ok_and(|parsed| parsed.hyphenated().to_string() == id)
            }) {
                std::fs::remove_file(entry.path()).map_err(|_| HistoryError::StorageWrite)?;
            }
        }
        Ok(())
    }

    pub(crate) fn save(
        &self,
        provider_id: &str,
        account_id: &str,
        history: &CompleteHistory,
    ) -> Result<(), HistoryError> {
        if !history.coverage.complete {
            return Err(HistoryError::IncompleteSnapshot);
        }
        if history.account_id != account_id {
            return Err(HistoryError::SnapshotAccountMismatch);
        }
        if !valid_history(history, account_id) {
            return Err(HistoryError::StorageInvalid);
        }
        let path = self.document_path(provider_id, account_id)?;
        let _lock_file = self.lock()?;
        if self
            .read_document_locked(&path, account_id)?
            .is_some_and(|stored| !history_is_at_least_as_new(history, &stored.history))
        {
            return Ok(());
        }
        // Cache one complete result, including when its coverage overlaps a prior result.
        // Legacy archives disappear on the next successful save; counts are never added.
        let content = serde_json::to_string(&HistoryDocument {
            version: 3,
            history: history.clone(),
            archived: None,
        })
        .map_err(|_| HistoryError::StorageWrite)?;
        crate::safe_file::write_text(&path, &content).map_err(|_| HistoryError::StorageWrite)
    }

    fn lock(&self) -> Result<std::fs::File, HistoryError> {
        std::fs::create_dir_all(&self.root).map_err(|_| HistoryError::StorageWrite)?;
        let lock_file = OpenOptions::new()
            .create(true)
            .read(true)
            .write(true)
            .open(self.root.join(HISTORY_LOCK_FILE_NAME))
            .map_err(|_| HistoryError::StorageWrite)?;
        lock_file.lock().map_err(|_| HistoryError::StorageWrite)?;
        Ok(lock_file)
    }

    pub(super) fn document_path(
        &self,
        provider_id: &str,
        account_id: &str,
    ) -> Result<PathBuf, HistoryError> {
        if !valid_component(provider_id) || !valid_component(account_id) {
            return Err(HistoryError::InvalidStorageKey);
        }
        Ok(self
            .root
            .join(provider_id)
            .join(format!("{account_id}.json")))
    }
}

fn same_period(left: &CompleteHistory, right: &CompleteHistory) -> bool {
    match (&left.coverage.billing_cycle, &right.coverage.billing_cycle) {
        (Some(left), Some(right)) => left == right,
        (None, None) => {
            left.coverage.from_ms == right.coverage.from_ms
                && left.coverage.to_ms == right.coverage.to_ms
                && left.coverage.time_zone == right.coverage.time_zone
                && left.coverage.scope == right.coverage.scope
        }
        _ => false,
    }
}

fn valid_history(history: &CompleteHistory, account_id: &str) -> bool {
    let coverage = &history.coverage;
    history.account_id == account_id
        && coverage.complete
        && coverage.from_ms > 0
        && coverage.from_ms < coverage.to_ms
        && jiff::tz::TimeZone::get(&coverage.time_zone).is_ok()
        && coverage.billing_cycle.as_ref().is_none_or(|cycle| {
            cycle.start_ms > 0
                && cycle.start_ms <= coverage.from_ms
                && cycle.end_ms >= coverage.to_ms
        })
}

fn history_is_at_least_as_new(incoming: &CompleteHistory, stored: &CompleteHistory) -> bool {
    incoming.coverage.fetched_at_ms > stored.coverage.fetched_at_ms
        || (incoming.coverage.fetched_at_ms == stored.coverage.fetched_at_ms
            && incoming.coverage.to_ms >= stored.coverage.to_ms)
}

fn valid_component(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= 160
        && value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.'))
        && value != "."
        && value != ".."
}
